{{- if .Values.mcpPvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ibm-operations-agent-z-mcp-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    {{- range .Values.mcpPvc.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.mcpPvc.size }}
  {{- if .Values.mcpPvc.storageClass }}
  storageClassName: {{ .Values.mcpPvc.storageClass }}
  {{- end }}
{{- end }}
