{{- if .Values.bootstrapJob.enabled }}
{{- $isGranite := contains "granite-3-3-8b-instruct" .Values.env.WATSONX_MODEL_ID }}
{{- $modelRuntime := default "" (or (get (get (get (get .Values "global" | default dict) "secrets" | default dict) "data" | default dict) "MODEL_RUNTIME") (get (get .Values "env" | default dict) "MODEL_RUNTIME")) -}}
{{- $isOpenAI := contains "openai_protocol" $modelRuntime }}
{{- $supportAgentFile := ternary "config/support_agent_granite.yaml" "config/support_agent.yaml" $isGranite }}
{{- $supportAgentContent := .Files.Get $supportAgentFile }}

{{- if and $isGranite $isOpenAI }}
  {{- $supportAgentContent = $supportAgentContent | replace "virtual-model/watsonx/ibm/granite-3-3-8b-instruct" "virtual-model/openai/ibm/granite-3-3-8b-instruct" }}
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-bootstrap-config
  annotations:
    {{- include "wxa4z.annotations" . | nindent 4 }}
data:
  support_agent_bootstrap_config.yaml: |-
{{ .Files.Get "config/support_agent_bootstrap_config.yaml" | indent 4 }}
  
  support_agent.yaml: |-
{{- $supportAgentContent | nindent 4 }}

{{- end }}