{{- $api := coalesce .Values.global.secrets.data.EXTERNAL_WATSONX_API_KEY .Values.global.secrets.data.WATSONX_API_KEY -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secrets.name }}
  annotations: 
    {{- include "wxa4z.annotations" . | nindent 4 }}
type: Opaque
data:
  ORCHESTRATE_ENV_TYPE: {{ .Values.global.secrets.data.ORCHESTRATE_ENV_TYPE | b64enc }}
  ORCHESTRATE_API_KEY: {{ .Values.global.secrets.data.WATSONX_API_KEY | b64enc }}
  ORCHESTRATE_ENV_URL: {{ .Values.global.secrets.data.ORCHESTRATE_ENV_URL | b64enc }}
  CPD_USERNAME: {{ .Values.global.secrets.data.CPD_USERNAME | b64enc }}
  WATSONX_DEPLOYMENT_SPACE_ID: {{ .Values.global.secrets.data.WATSONX_DEPLOYMENT_SPACE_ID | default "" | b64enc | quote }}
  WATSONX_ML_URL: {{ .Values.global.secrets.data.WATSONX_ML_URL | default "" | b64enc }}
  WATSONX_API_KEY: {{ $api | default "" | b64enc }}
  WATSONX_PROJECT_ID: {{ .Values.global.secrets.data.WATSONX_PROJECT_ID | default "" | b64enc | quote }}
  MODEL_RUNTIME: {{ required "MODEL_RUNTIME is required. Use on-prem | cloud for Watsonx runtime, or openai_protocol for OpenAI-compatible inference runtimes." .Values.global.secrets.data.MODEL_RUNTIME | default "" | b64enc | quote }} #  on-prem for watsonx ai on cpd,"cloud" for watsonx ai on saas, openai_protocol for inferencing stack with open ai protocol.
  LLM_BASE_URL:  {{ .Values.global.secrets.data.LLM_BASE_URL | default "" | b64enc | quote }} # Set this to inferencing stack url when MODEL_RUNTIME is set to openai_protocol
  LLM_API_KEY: {{ .Values.global.secrets.data.LLM_API_KEY | default "" | b64enc | quote }} # Set this to inferencing stack API KEY when MODEL_RUNTIME is set to openai_protocol
