apiVersion: wxa4z.watsonx.ibm.com/v1alpha1
kind: AgentService
metadata:
  name: zos-agent
  namespace: "" # namespace where the agent service will be deployed
  labels:
    wxa4z.watsonx.ibm.com/managed-by: agent-operator

spec:
  releaseName: zos-agent # release name for the helm chart deployment
  tenantId: "" # tenant id for which the agent service will be deployed
  namespace: "" # namespace where the agent service will be deployed
  wxa4z-core-services-namespace: "wxa4z-zad" # namespace where the wxa4z core services are deployed, default is "wxa4z-zad"

  agentDetails:
    - agentName: zosconfig
      agentId: wxa4z:zosconfig:agent # unique identifier for the agent, format should be <wxa4z>:<agent_name>:agent
      description: "The IBM Agents for z/OS configuration agent can take queries about the configuration of your z/OS systems, such as how to enable SMF tracing or what libraries are currently listed in LNKLST"
      agentDisplayName: "IBM Agent for z/OS" # display name for the agent
      bootstrapConfig:
        name: "zos-agent-bootstrap-config" # name of the configmap that contains the bootstrap configuration for the agent
        fileName: "zos_agent_bootstrap_config.yaml" # file name of the file inside the configmap that contains the bootstrap configuration for the agent

  chart:
    repository: oci://icr.io/wxa4z-dev-container-registry # OCI registry where the helm chart is stored
    name: zos-agent # name of the helm chart
    version: "1.0.0" # version of the helm chart
    # pullSecrets: # pullSecrets is used to pull image from registry
    #   - name: pull-secret

  values:
    replicaCount: 1
    global: # global secrets "wxa4z-watsonx-credentials" which contains all the credentials.
      secrets:
        name: wxa4z-watsonx-credentials
    secrets: # secrets specific to the agent
      name: wxa4z-zos-agent-secrets
    env: # environment variables to be passed to the agent container which needs to be dynamic and can be used to pass any configuration details to the agent, these will be available as env variables in the agent container
      WATSONX_MODEL_ID: "ibm/granite-4.1-8b"
      DEPLOYMENT_TYPE: "on‑prem"
      MODEL_RUNTIME: "openai_protocol"


