{{- /* OpenShift Route: include certs only when DEPLOYMENT_TYPE=on-prem AND termination=edge */ -}}
{{- $depType    := lower (default "on-prem" .Values.env.DEPLOYMENT_TYPE) -}}
{{- $isCloud    := eq $depType "cloud" -}}
{{- $nsRelease  := .Release.Namespace -}}
{{- $name       := required "route.name is required" .Values.route.name -}}
{{- $svc        := required "route.serviceName is required" .Values.route.serviceName -}}
{{- $tgtPort    := default "http" .Values.route.targetPort -}}
{{- $weight     := default 100 .Values.route.weight -}}
{{- $hostGen    := default "true" .Values.route.annotations.hostGenerated -}}
{{- $secretName := default "wxa4z-agents-tls-secret" .Values.route.tls.secretName -}}
{{- $termOnPrem := default "edge" .Values.route.tls.termination -}}

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $name }}
  annotations:
    openshift.io/host.generated: "{{ $hostGen }}"
    haproxy.router.openshift.io/timeout: "1m"
    haproxy.router.openshift.io/hsts_header: max-age=31536000; includeSubDomains; preload
    router.openshift.io/cookie-same-site: Strict
    haproxy.router.openshift.io/header-set: |
      Content-Security-Policy: "default-src 'none';"
spec:
  to:
    kind: Service
    name: {{ $svc }}
    weight: {{ $weight }}
  port:
    targetPort: {{ $tgtPort }}
  tls:
    # Cloud: always edge (no certs). On-prem: use value (default edge).
    termination: {{ if $isCloud }}edge{{ else }}{{ $termOnPrem }}{{ end }}
    insecureEdgeTerminationPolicy: Redirect
    {{- /* Only inject certs when on-prem AND termination=edge */ -}}
    {{- if and (not $isCloud) (eq (lower $termOnPrem) "edge") }}
    {{- $sec := lookup "v1" "Secret" $nsRelease $secretName -}}
    {{- with (and $sec (index $sec.data "tls.crt")) }}
    certificate: |-
      {{ . | b64dec | nindent 6 }}
    {{- end }}
    {{- with (and $sec (index $sec.data "tls.key")) }}
    key: |-
      {{ . | b64dec | nindent 6 }}
    {{- end }}
    {{- with (and $sec (index $sec.data "ca.crt")) }}
    caCertificate: |-
      {{ . | b64dec | nindent 6 }}
    {{- end }}
    {{- end }}
