apiVersion: v1
kind: Service
metadata:
  name: {{ required "service.name is required" .Values.service.name }}
spec:
  selector:
    app: {{ required "Chart.Name is required" .Chart.Name }}
  ports:
    - name: {{ required "service.ports.name is required" .Values.service.ports.name }}
      protocol: {{ required "service.ports.protocol is required" .Values.service.ports.protocol }}
      port: {{ required "service.ports.port is required" .Values.service.ports.port }}
      targetPort: {{ required "service.ports.targetPort is required" .Values.service.ports.targetPort }}