
apiVersion: wxa4z.watsonx.ibm.com/v1alpha1
kind: AgentService
metadata:
  name: zrag-agent
  namespace: ""
  labels:
    wxa4z.watsonx.ibm.com/managed-by: agent-operator
spec:
  releaseName: zrag-agent
  tenantId: ""
  namespace: ""
  wxa4z-core-services-namespace: wxa4z-zad
  agentDetails:
      - agentName: zrag-agent
        agentId: wxa4z:zrag-agent:agent
        description: zrag-agent description"
        bootstrapConfig:
          name: "zrag-agent-bootstrap-config"
          fileName: "zrag_agent_bootstrap_config.yaml"
  chart:
    repository: oci://icr.io/wxa4z-dev-container-registry
    name: zrag-agent
    version: "1.0.0"
    # pullSecrets:
    #   - name: pull-secret

  values:
    replicaCount: 1
    global:
        secrets:
            name: wxa4z-watsonx-credentials
    secrets:
      name: wxa4z-zrag-agent-secrets
    env:
      CPD_VERSION: "5.2"
      ONPREM_WML_INSTANCE_ID: "openshift"
      WATSONX_MODEL_ID: "meta-llama/llama-3-3-70b-instruct"
      ENABLE_DOC_INGESTION: "false"
      HOST_NAME: "apps.wxa4z311-cpd530-x86-qa.cp.fyre.ibm.com"
      LANGFUSE_ENABLED: false
      DEPLOYMENT_TYPE: "on-prem"
      MODEL_RUNTIME : "on-prem"
