{{- if .Values.secrets.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    "wxa4z.ibm.com/agent": "true"
type: Opaque
data:
  CPD_USERNAME: {{ .Values.secrets.data.CPD_USERNAME | b64enc }}
  ENCRYPT_KEY: {{ .Values.secrets.data.ENCRYPT_KEY | b64enc }}
  AGENT_AUTH_TOKEN: {{ .Values.secrets.data.AGENT_AUTH_TOKEN | b64enc }}
  LLM_MODEL: {{ .Values.env.WATSONX_MODEL_ID | b64enc}}
  LANGFUSE_PUBLIC_KEY: {{ .Values.secrets.data.LANGFUSE_PUBLIC_KEY | b64enc }}
  LANGFUSE_SECRET_KEY: {{ .Values.secrets.data.LANGFUSE_SECRET_KEY | b64enc }}
  WATSONX_DEPLOYMENT_SPACE_ID: {{ .Values.env.WATSONX_DEPLOYMENT_SPACE_ID | b64enc }}
  WATSONX_ML_URL: {{ .Values.env.WATSONX_ML_URL | b64enc }}
  WATSONX_API_KEY: {{ .Values.secrets.data.WATSONX_API_KEY | b64enc }}
  WATSONX_PROJECT_ID: {{ .Values.env.WATSONX_PROJECT_ID | b64enc }}
{{- end }}
