apiVersion: wxa4z.watsonx.ibm.com/v1alpha1
kind: AgentService
metadata:
  name: compiler-fix-finder-agent
  namespace: "" #namespace where the agent service will be deployed
  labels:
    wxa4z.watsonx.ibm.com/managed-by: agent-operator

spec:
  releaseName: compiler-fix-finder-agent # release name for the helm chart deployment
  tenantId: "" # tenant id for which the agent service will be deployed
  namespace: "" # namespace where the agent service will be deployed
  wxa4z-core-services-namespace: wxa4z-zad # namespace where the wxa4z core services are deployed, default is "wxa4z-zad"

  agentDetails:
    - agentName: compiler-fix-finder-agent
      agentId: wxa4z:compiler-fix-finder-agent:agent # unique identifier for the agent, format should be <wxa4z>:<agent_name>:agent
      description: "This agent helps users to search errors for IBM COBOL for Z compiler fixes"
      agentDisplayName: "IBM Z Compilers Fix Finder Agent" # display name for the agent
      bootstrapConfig:
        name: "compiler-fix-finder-agent-bootstrap-config" # name of the configmap that contains the bootstrap configuration for the agent
        fileName: "compiler_fix_finder_agent_bootstrap_config.yaml" # file name of the file inside the configmap that contains the bootstrap configuration for the agent

  chart:
    name: compiler-fix-finder-agent # name of the helm chart
    repository: oci://icr.io/zoscp-sandbox/charts # OCI registry namespace where the helm chart is stored
    version: "1.1.3" # version of the helm chart
    pullSecrets: # pullSecrets is used to pull image from registry
      - name: z-compiler-fix-finder-image-pull-secret
  values:
    replicaCount: 1
    global: # gobal secerts "wxa4z-watsonx-credentials" which contains all the credentials.
      secrets:
        name: wxa4z-watsonx-credentials
    secrets: # secrets specific to the agent which needs to container
      name: wxa4z-compiler-fix-finder-agent-secrets
    env: # environment variables to be passed to the agent container which needs to dynamic and can be used to pass any configuration details to the agent, these will be available as env variables in the agent container
      WATSONX_MODEL_ID: "ibm/granite-4.1-8b"
      MODEL_RUNTIME: "openai_protocol"
      MAX_COMPLETION_TOKENS: 4096
      LANGFUSE_HOST: "LANGFUSE_HOST"
      LANGFUSE_TRACING_ENABLED: false
      LANGFUSE_ENABLED: false
      MAJOR_APAR_FIRST: true
      PUBLIC_APAR_FOCUS: false
      DEBUG_MODE: true