apiVersion: wxa4z.watsonx.ibm.com/v1alpha1
kind: AgentService
metadata:
  name: ibm-concert-agent-z
  namespace: "" #namespace where the agent service will be deployed
  labels:
    wxa4z.watsonx.ibm.com/managed-by: agent-operator

spec:
  releaseName: ibm-concert-agent-z # release name for the helm chart deployment
  tenantId: "" # tenant id for which the agent service will be deployed
  namespace: "" # namespace where the agent service will be deployed
  wxa4z-core-services-namespace: "" # namespace where the wxa4z core services are deployed, default is "wxa4z-zad"

  agentDetails:
    - agentName: ibm-concert-agent-z
      agentId: wxa4z:ibm-concert-agent-z:agent # unique identifier for the agent, format should be <wxa4z>:<agent_name>:agent
      description: "Provides list of critical events from the system. Provides analyze the WLM goals information. Provides WLM utilization of the event and give a summary. Can answer, questions related to retrieving critical events from systems and analyzing WLM utilization."
      agentDisplayName: "IBM Concert for Z Agent" # display name for the agent
      bootstrapConfig:
        name: "ibm-concert-agent-z-bootstrap-config" # name of the configmap that contains the bootstrap configuration for the agent
        fileName: "ibm_concert_agent_bootstrap_config.yaml" # file name of the file inside the configmap that contains the bootstrap configuration for the agent

  chart:
    repository: oci://icr.io/wxa4z-agentic-dev-cr # OCI registry where the helm chart is stored
    name: ibm-concert-agent-z # name of the helm chart
    version: "1.1.2" # version of the helm chart
    # pullSecrets: # pullSecrets is used to pull image from registry
    #   - name: pull-secret
  values:
    replicaCount: 1
    global: # gobal secerts "wxa4z-watsonx-credentials" which contains all the credentials.
      secrets:
        name: wxa4z-watsonx-credentials
    secrets: # secrets specific to the agent which needs to container
      name: ibm-concert-agent-z-mcp-secrets
    env: # environment variables to be passed to the agent container which needs to dynamic and can be used to pass any configuration details to the agent, these will be available as env variables in the agent container
      WATSONX_MODEL_ID: ""
      MODEL_RUNTIME: "openai_protocol"




