{{- if .Values.secrets.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    "wxa4z.ibm.com/agent": "true"
  annotations:
    {{- include "wxa4z.annotations" . | nindent 4 }}
type: Opaque
data:
  CPD_USERNAME: {{ .Values.secrets.data.CPD_USERNAME | b64enc }}
  WATSONX_PASSWORD: {{ .Values.secrets.data.WATSONX_PASSWORD | b64enc }}
  WATSONX_API_KEY: {{ .Values.secrets.data.WATSONX_API_KEY | b64enc }}
  WATSONX_ML_URL:  {{ .Values.env.WATSONX_ML_URL | b64enc }}
  WATSONX_DEPLOYMENT_SPACE_ID: {{ .Values.env.WATSONX_DEPLOYMENT_SPACE_ID | b64enc }}
  WATSONX_PROJECT_ID: {{ .Values.env.WATSONX_PROJECT_ID | b64enc }}
{{- end }}