apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.PDnetworkPolicy.name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Chart.Name }}-pd
  policyTypes:
  - Egress
  - Ingress
  {{- with .Values.PDnetworkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.PDnetworkPolicy.egress}}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}