{{- if .Values.PDsecrets.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.PDsecrets.name }}
  labels:
    "wxa4z.ibm.com/agent": "true"
type: Opaque
stringData:
  WRAPPER_PASSWORD: {{  .Values.PDsecrets.data.WRAPPER_PASSWORD }}
  WRAPPER_USERNAME: {{ .Values.PDsecrets.data.WRAPPER_USERNAME }}
  WRAPPER_URL: {{ .Values.PDsecrets.data.WRAPPER_URL }}
  INGESTION_URL: {{  .Values.PDsecrets.data.INGESTION_URL }}
  INGESTION_PASSWORD: {{ .Values.PDsecrets.data.INGESTION_PASSWORD }}
  MCP_SERVER_URL: {{ required "MCP_SERVER_URL is required" .Values.PDsecrets.data.MCP_SERVER_URL }}
  APPLID: {{ .Values.PDsecrets.data.APPLID }}
  AGENT_ID: {{ .Values.PDsecrets.data.AGENT_ID }}
  AUTH_SERVICE_BASE_URL: {{ .Values.PDsecrets.data.AUTH_SERVICE_BASE_URL }}
  AGENT_AUTH_TOKEN: {{ required "AGENT_AUTH_TOKEN is required" .Values.PDsecrets.data.AGENT_AUTH_TOKEN }}
  WATSONX_MODEL_ID: {{ required "WATSONX_MODEL_ID is required" .Values.env.WATSONX_MODEL_ID }}
  CPD_USERNAME: {{ .Values.PDsecrets.data.CPD_USERNAME }}
  LLM_MODEL: {{ required "WATSONX_MODEL_ID is required" .Values.env.WATSONX_MODEL_ID}}
  LANGFUSE_PUBLIC_KEY: {{ .Values.PDsecrets.data.LANGFUSE_PUBLIC_KEY | b64enc }}
  LANGFUSE_SECRET_KEY: {{ .Values.PDsecrets.data.LANGFUSE_SECRET_KEY | b64enc }}
  WATSONX_DEPLOYMENT_SPACE_ID: {{ .Values.env.WATSONX_DEPLOYMENT_SPACE_ID | b64enc }}
  WATSONX_ML_URL: {{ .Values.env.WATSONX_ML_URL | b64enc }}
  WATSONX_API_KEY: {{ .Values.secrets.data.WATSONX_API_KEY | b64enc }}
  WATSONX_PROJECT_ID: {{ .Values.secrets.data.WATSONX_PROJECT_ID | b64enc }}
  ACTIVE_AGENT: {{ .Values.PDsecrets.data.ACTIVE_AGENT }}
  SERVICE_ENDPOINT: {{ .Values.PDsecrets.data.SERVICE_ENDPOINT }}
{{- end -}}