apiVersion: v1
kind: Service
metadata:
  name: {{ required "service.name is required"  .Values.PDservice.name }}
spec:
  selector:
    app: {{ required "Chart.Name is required"  .Chart.Name }}-pd
  ports:
    - name: {{ required "service.ports.name is required" .Values.PDservice.ports.name }}
      protocol: {{ required "service.ports.protocol is required" .Values.PDservice.ports.protocol }}
      port: {{ required "service.ports.port is required" .Values.PDservice.ports.port }}
      targetPort: {{ required "service.ports.targetPort is required" .Values.PDservice.ports.targetPort }}
