apiVersion: wxa4z.watsonx.ibm.com/v1alpha1
kind: AgentService
metadata:
  name: ims-agent # eg: upgrade-agent-test
  namespace: wxa4z-<>
  labels:
    wxa4z.watsonx.ibm.com/managed-by: agent-operator

spec:
  releaseName: ims-agent
  tenantId: ""
  namespace: wxa4z-<>
  wxa4z-core-services-namespace: wxa4z-zad # namespace in which the opensearch-client, authorization etc are deployed

  agentDetails:
    - agentName: ims
      agentId: wxa4z:ims:agent
      displayName: "IBM Z IMS Agent"
      description: "IMS AGENT helps to answer all IMS related questions"
      bootstrapConfig:
        name: ims-agent-bootstrap-config
        fileName: ims_agent_bootstrap_config.yaml

  chart:
    repository: oci://icr.io/ibm-ims-ai   # (oci://icr.io/wxa4z-dev-container-registry)
    name: ims-agent # (upgrade-agent)
    version: 1.1.0
    # pullSecrets: # if not mentioned in CR, by default will search in the secret - pull-secret
    #   - name: ims-chart-secret # the name of the secret containing the credentials for the image repo of the agent so that the tar.gz can be pulled

  values:
    replicaCount: 1

    global:
      secrets:
        name: wxa4z-watsonx-credentials # this should be provided in the CR so that the global variables can be referenced

    secrets:
      name: wxa4z-ims-agent-secrets # upgrade-agent-secrets (this secret is about each agent)

    env: # below are samples of configurable environment variables
      DEPLOYMENT_TYPE: "on-prem"
      WATSONX_MODEL_ID: ibm/granite-4.1-8b #openai/gpt-oss-120b #"ibm/granite-3-3-8b-instruct"
      AUTHZ_BASE_URL: ""  #openshift authorization route from wxa4z-zad namespace
      MODEL_RUNTIME: "openai_protocol"

    
    registry:
      entitlementKey: ""